### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type Long

### ISSUE THREAD

**Issue by MrLinNing** [AlphaPav/DBA#1]
My torch version is 1.3.1, and I can normally run the mnist_params.yaml.
But the problem happened when I run the other three dataset.
```
Traceback (most recent call last):
  File "main.py", line 179, in <module>
    epoch_interval=helper.params['aggr_epoch_interval'])
  File "/DBA/helper.py", line 256, in average_shrink_models
    data.add_(update_per_layer)
RuntimeError: result type Float can't be cast to the desired output type Long
```
So, can you help me with that?

**Comment by AlphaPav** [comment]
Oh I am so sorry for my late reply......
I think you can transfer the type like this: 
https://github.com/AI-secure/DBA/blob/4f1dc0c92a9b92aa1bc537e8fa239040ece864e2/helper.py#L415

Best,
Chulin
