### ISSUE TITLE
when  I reproduce the experiment on tiny-imagenet dataset, the main task acc is very low,only 53%, why? what can I do to solve  the problem? thank you

### ISSUE THREAD

**Issue by JobsWangHaoQuan** [AlphaPav/DBA#11]

**Comment by AlphaPav** [comment]
Hi, did you use the pretrained model in the readme to start the experiments? 

As said in our paper, 
> In three image datasets, we begin to attack when the main accuracy of global model converges, which is round 10 for MNIST, 200 for CIFAR, 20 for Tiny-imagenet in Attack A-M
