### ISSUE TITLE
Thanks for your code, but the tiny-imagenet-200 url link is invalid

### ISSUE THREAD

**Issue by fengshaw1** [AlphaPav/DBA#13]
The link is invalid, can you provide it again?
![image](https://github.com/AI-secure/DBA/assets/57137032/21b5f05f-6676-44b4-9f44-dcbaa4411433)

**Comment by AlphaPav** [comment]
Thanks for your interest! 

I uploaded the dataset into this google drive link: https://drive.google.com/file/d/1wN09Fjl_2ZWNhoIGNmzWkarv7v_f4JOh/view?usp=sharing

**Comment by fengshaw1** [comment]
ok, thank you very much!!! nice work！
