### ISSUE TITLE
Script aborts for tiny_image dataset

### ISSUE THREAD

**Issue by jaintj95** [AlphaPav/DBA#2]
Issue: 
Script fails with a directory related error when executing 
`python main.py --params utils/tiny_params.yaml` 
![dba_error](https://user-images.githubusercontent.com/36858630/83859905-365a8600-a73c-11ea-9553-a2b2c4db248d.png)

What's strange here is that this is the first run. Then why is the script trying to "resume" a supposedly "trained" model?

Steps to reproduce:
`python -m visdom.server -p 8098` 

`python main.py --params utils/tiny_params.yaml`

**Comment by jaintj95** [comment]
Update: Nevermind. Looks like it has to do with config in .yaml file. 
@AlphaPav would be great if you could include yaml files for training from scratch

**Comment by AlphaPav** [comment]
Thanks for your suggestion!
