### ISSUE TITLE
extend poisoning patterns

### ISSUE THREAD

**Issue by anupamme** [AlphaPav/DBA#3]
Hello,

I am looking at the file utils/tiny_params.yaml and I see that there are four adversaries:

adversary_list: [0, 20, 74, 95]

and 4 adversaries and there are four adversary patterns: 

0_poison_pattern = [..]
1_poison_pattern = [..]
2_poison_pattern = [..]
3_poison_pattern = [..]

If we want to have 5 adversaries and 5 poison patterns, is there a way to calculate poison patterns programmatically (instead of hardcoding them).

Any pointer/help would be great.

**Comment by AlphaPav** [comment]
I'm so sorry..... I didn't get a notification from Github and I just saw the issue you raised...

The poison patterns are designed by attackers so we just use some simple and regular patterns and hardcoding them.
There are some optimization methods that can generate trigger patterns. See:
https://people.cs.uchicago.edu/~ravenben/publications/pdf/backdoor-sp19.pdf
https://www.ijcai.org/Proceedings/2019/647

Best,
Chulin
