### ISSUE TITLE
Aggregation of gradients in FoolsGold has to be done at external epochs also

### ISSUE THREAD

**Issue by Chakravarti-Baratam** [AlphaPav/DBA#4]
Aggregation of gradients in FoolsGold code is happening after internal epochs in one external epoch.
As per 'Mitigating Sybils in Federated Learning Poisoning' paper, aggregation should also happen after every external epoch. After each external epoch, we need to calculate aggregate historical vector. Currently in the code, this is not happening.

**Comment by AlphaPav** [comment]
Thanks for your interest! 
We can calculate the aggregate historical vector by setting  'self.use_memory = True’ https://github.com/AI-secure/DBA/blob/4f1dc0c92a9b92aa1bc537e8fa239040ece864e2/helper.py#L532
